using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

/// <summary>
/// The title screen: full-bleed key art under a logo lockup, with the thirteen
/// game modes dealt out as painted cards in three named decks.
///
/// The cards used to be thirteen live 3D dioramas, each with its own camera and
/// render texture. They showed the real robots, which was the appeal, but
/// thirteen extra renders of a post-processed scene cost more than the game
/// behind them and the menu ran at a few frames a second. They are painted
/// stills now (Assets/Resources/Menu, generated by Tools/menuart.py), which is
/// also what a mode-select screen looks like in a shipped game: art directed to
/// sell the mode, not a live view of it.
/// </summary>
public static class MainMenu
{
    // -- palette ---------------------------------------------------------
    static readonly Color Ink = new Color(0.012f, 0.035f, 0.062f);
    static readonly Color CardBed = new Color(0.05f, 0.10f, 0.16f, 1f);
    static readonly Color Combat = new Color(0.25f, 0.84f, 1f);
    static readonly Color Command = new Color(1f, 0.62f, 0.24f);
    static readonly Color Academy = new Color(0.76f, 0.56f, 1f);
    static readonly Color GoldTop = new Color(1f, 0.97f, 0.82f);
    static readonly Color GoldLow = new Color(0.97f, 0.58f, 0.11f);

    // -- layout, on the 1920x1080 reference canvas ------------------------
    // Three decks side by side: 3 columns, then 2, then 2. The widths below
    // total 1736, which centres inside 1920 with a 92px margin either side.
    const float CardW = 224f, CardH = 126f;      // exactly 16:9, like the art
    const float PitchX = 238f, PitchY = 140f;
    const float HeaderY = -58f, Row0Y = -155f, Row1Y = Row0Y - PitchY;

    const string DesktopHint =
        "WASD move   ·   Mouse aim   ·   LMB fire   ·   Space jump   ·   T transform   ·   Z scope";

    static Text _hint;
    static InputField _seedField;
    static int _modeCount;          // tallied as the decks are dealt

    /// <summary>
    /// The MAP CODE the player typed for Commander or Tower Defense, or null
    /// for "roll one". Codes are how a map is revisited: every battlefield
    /// prints its code in the overlay, and typing it here rebuilds that
    /// exact map — in whichever strategy mode is launched next.
    /// </summary>
    public static int? RequestedSeed
    {
        get
        {
            if (_seedField == null || string.IsNullOrWhiteSpace(_seedField.text))
                return null;
            return int.TryParse(_seedField.text.Trim(), out int seed) ? seed : (int?)null;
        }
    }

    struct Mode
    {
        public string label;
        public string art;          // a texture under Resources/Menu
        public UnityAction go;

        public Mode(string label, string art, UnityAction go)
        {
            this.label = label;
            this.art = art;
            this.go = go;
        }
    }

    public static GameObject Build(GameModeController controller)
    {
        var canvasGo = new GameObject("MainMenu");
        canvasGo.transform.SetParent(controller.transform, false);
        var canvas = canvasGo.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 20;
        var scaler = canvasGo.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);
        scaler.matchWidthOrHeight = 0.5f;
        canvasGo.AddComponent<GraphicRaycaster>();

        EnsureEventSystem();

        _modeCount = 0;
        BuildBackdrop(canvasGo.transform);
        BuildTitle(canvasGo.transform);

        // One parent for every card, so a hovered card raising itself to the
        // front can never climb over the title or the footer.
        var decks = MakeRect(canvasGo.transform, "Decks");
        Stretch(decks);

        // Row one of each deck is the headline mode, row two its variants.
        BuildDeck(decks, "ARENA  COMBAT", Combat, -868f, 3, new[]
        {
            new Mode("AI  v  AI", "aivai", () => controller.OpenRobotSelect(GameMode.AIvAI)),
            new Mode("PLAYER  v  AI", "playervsai", () => controller.OpenRobotSelect(GameMode.PlayerVsAI)),
            new Mode("ONLINE  PVP", "onlinepvp", () => OnlineMenu.Open(controller, canvasGo)),
            new Mode("BRAWL", "brawl", () => controller.OpenRobotSelect(GameMode.Brawl)),
            new Mode("BRAWL:  AI  WAR", "brawlwar", () => controller.OpenRobotSelect(GameMode.BrawlWar)),
            new Mode("MARTIAL  ARTS  SHOW", "brawlshow", () => controller.OpenRobotSelect(GameMode.BrawlShow)),
        });
        BuildDeck(decks, "WAR  ROOM", Command, -112f, 2, new[]
        {
            new Mode("COMMANDER", "commander", controller.StartCommander),
            new Mode("COMMANDER:  AI  WAR", "commanderwar", controller.StartCommanderWar),
            new Mode("TOWER  DEFENSE", "towerdefense", controller.StartTowerDefense),
            new Mode("TANK  RAID", "tankraid", () => controller.OpenRobotSelect(GameMode.TankRaid)),
        });
        BuildDeck(decks, "ACADEMY  ·  WORKSHOP", Academy, 406f, 2, new[]
        {
            new Mode("CHINESE  QUEST", "chinesequest", controller.OpenChineseDeckSelect),
            new Mode("CHINESE  RUN", "chineserun", controller.OpenChineseRunDeckSelect),
            new Mode("ARENA  BUILDER", "arenabuilder", controller.StartArenaPreview),
        });

        BuildFooter(canvasGo.transform, controller);
        return canvasGo;
    }

    // -- background ------------------------------------------------------

    /// <summary>
    /// Key art, then the two scrims that make text land on it. The sky scrim
    /// deepens the top so the logo has contrast; the deck scrim sinks the
    /// bottom so the cards read as a panel rather than as clutter on a
    /// photograph. Both are smoothstepped, which is what keeps them from
    /// showing a band where they meet the art.
    /// </summary>
    static void BuildBackdrop(Transform parent)
    {
        // Under everything, in case the art fails to load: the screen must
        // never fall through to the live arena behind the canvas.
        var bed = MakeImage(parent, "Bed", Ink);
        Stretch(bed.rectTransform);

        var viewport = MakeRect(parent, "KeyArtViewport");
        Stretch(viewport);
        viewport.gameObject.AddComponent<RectMask2D>();   // clips the overscan

        // The drift lives on its own transform between the viewport and the
        // art. AspectRatioFitter rewrites anchoredPosition to zero on every
        // layout pass in its envelope modes, so anything animating position on
        // the fitted object itself is silently reset each frame.
        var drifter = MakeRect(viewport, "KeyArtDrift");
        Stretch(drifter);
        drifter.gameObject.AddComponent<MenuKenBurns>();

        var art = new GameObject("KeyArt").AddComponent<RawImage>();
        art.rectTransform.SetParent(drifter, false);
        art.texture = Resources.Load<Texture2D>("Menu/keyart");
        art.raycastTarget = false;
        // Envelope rather than stretch: on an ultrawide or a phone the art
        // must crop, not squash.
        var fitter = art.gameObject.AddComponent<AspectRatioFitter>();
        fitter.aspectMode = AspectRatioFitter.AspectMode.EnvelopeParent;
        fitter.aspectRatio = 16f / 9f;

        var sky = MakeImage(parent, "SkyScrim", new Color(Ink.r, Ink.g, Ink.b, 0.62f));
        sky.sprite = MenuArt.FadeDown();
        Band(sky.rectTransform, top: true, height: 500f);

        // The deck sits on a flat tray, not on a gradient. A single bottom-up
        // fade cannot hold an even tone across 270px of cards — it is always
        // still climbing at the top row and already saturated at the bottom
        // one, which left the upper cards fighting the art behind them. So:
        // a feathered lip to get down off the key art, then a constant slab.
        var lip = MakeImage(parent, "TrayLip", new Color(Ink.r, Ink.g, Ink.b, 0.72f));
        lip.sprite = MenuArt.FadeUp();
        Strip(lip.rectTransform, centreY: 70f, height: 120f);

        var tray = MakeImage(parent, "Tray", new Color(Ink.r, Ink.g, Ink.b, 0.72f));
        Band(tray.rectTransform, top: false, height: 550f);

        // A last touch of weight along the very bottom edge, so the tray reads
        // as depth rather than as a flat rectangle laid over the picture.
        var floor = MakeImage(parent, "TrayFloor", new Color(Ink.r, Ink.g, Ink.b, 0.35f));
        floor.sprite = MenuArt.FadeUp();
        Band(floor.rectTransform, top: false, height: 300f);

        var vignette = MakeImage(parent, "Vignette", new Color(Ink.r, Ink.g, Ink.b, 0.60f));
        vignette.sprite = MenuArt.Vignette();
        Stretch(vignette.rectTransform);
    }

    // -- logo lockup -----------------------------------------------------

    /// <summary>
    /// Crest, then the title stacked over a ruled subtitle. The two title
    /// lines are legacy Text — this project has no TextMeshPro essentials —
    /// so the metal look is built from three stacked mesh effects rather than
    /// from a font feature: a vertex gradient for the gold, a fat dark outline
    /// for the keyline, and an offset shadow for the lift.
    ///
    /// It all sits above canvas y +200, which is the empty sky the key art was
    /// composed to leave; the tallest robot antenna reaches only +113.
    /// </summary>
    static void BuildTitle(Transform parent)
    {
        var crest = new GameObject("Emblem").AddComponent<RawImage>();
        crest.rectTransform.SetParent(parent, false);
        crest.texture = Resources.Load<Texture2D>("Menu/emblem");
        crest.raycastTarget = false;
        Place(crest.rectTransform, new Vector2(0f, 448f), new Vector2(160f, 160f));

        var justice = MakeText(parent, "Justice", "J U S T I C E", 48, Color.white,
            FontStyle.Bold, new Vector2(0f, 352f), new Vector2(1400f, 70f));
        Gild(justice, keyline: 3f);

        var heroes = MakeText(parent, "ArmoredHeroes", "ARMORED  HEROES", 92, Color.white,
            FontStyle.Bold, new Vector2(0f, 282f), new Vector2(1600f, 120f));
        Gild(heroes, keyline: 5f);

        // A ruled subtitle: two hairlines with the tagline between them.
        var tag = MakeText(parent, "Tagline", "THE  TRANSFORMING  ROBOT  BATTLE  LEAGUE", 20,
            new Color(1f, 1f, 1f, 0.72f), FontStyle.Normal, new Vector2(0f, 212f),
            new Vector2(900f, 30f));

        foreach (int side in new[] { -1, 1 })
        {
            var rule = MakeImage(parent, "TagRule", new Color(1f, 0.82f, 0.45f, 0.45f));
            Place(rule.rectTransform, new Vector2(side * 350f, 212f), new Vector2(160f, 1f));
        }
    }

    /// <summary>Gold-gradient face, dark keyline, dropped shadow.</summary>
    static void Gild(Text text, float keyline)
    {
        var gradient = text.gameObject.AddComponent<UIGradient>();
        gradient.top = GoldTop;
        gradient.bottom = GoldLow;

        // Added after the gradient on purpose — see UIGradient's note on
        // mesh-modifier ordering.
        var outline = text.gameObject.AddComponent<Outline>();
        outline.effectColor = new Color(0.02f, 0.06f, 0.11f, 0.95f);
        outline.effectDistance = new Vector2(keyline, keyline);

        var shadow = text.gameObject.AddComponent<Shadow>();
        shadow.effectColor = new Color(0f, 0.02f, 0.05f, 0.55f);
        shadow.effectDistance = new Vector2(0f, -keyline * 1.6f);
    }

    // -- mode decks ------------------------------------------------------

    /// <summary>
    /// One named deck of cards. <paramref name="left"/> is the deck's left
    /// edge and <paramref name="cols"/> how many cards it deals per row, so
    /// decks of different sizes still line up on a shared baseline.
    /// </summary>
    static void BuildDeck(Transform parent, string title, Color accent, float left, int cols,
        Mode[] modes)
    {
        float width = cols * PitchX - (PitchX - CardW);

        var bar = MakeImage(parent, $"DeckBar_{title}", accent);
        Place(bar.rectTransform, new Vector2(left + 2f, HeaderY), new Vector2(4f, 18f));

        var heading = MakeText(parent, $"DeckTitle_{title}", title, 20, accent, FontStyle.Bold,
            new Vector2(left + 16f, HeaderY), new Vector2(width, 26f));
        heading.alignment = TextAnchor.MiddleLeft;
        heading.rectTransform.pivot = new Vector2(0f, 0.5f);

        var rule = MakeImage(parent, $"DeckRule_{title}", new Color(1f, 1f, 1f, 0.12f));
        var ruleRect = rule.rectTransform;
        ruleRect.pivot = new Vector2(0f, 0.5f);
        Place(ruleRect, new Vector2(left, HeaderY - 19f), new Vector2(width, 1f));

        for (int i = 0; i < modes.Length; i++)
        {
            int col = i % cols, row = i / cols;
            float x = left + col * PitchX + CardW * 0.5f;
            BuildCard(parent, modes[i], accent, new Vector2(x, row == 0 ? Row0Y : Row1Y));
        }
        _modeCount += modes.Length;
    }

    /// <summary>
    /// One mode card: painted art in a rounded frame, its name burned into a
    /// shaded strip along the bottom, an accent rail in its deck's colour, and
    /// a halo that blooms on hover.
    ///
    /// The halo lives OUTSIDE the masked frame — the mask is what rounds the
    /// art's corners, and anything parented under it would be clipped away at
    /// exactly the edge the glow needs to spill past.
    /// </summary>
    static void BuildCard(Transform parent, Mode mode, Color accent, Vector2 at)
    {
        var slot = MakeRect(parent, $"Card_{mode.label}");
        Place(slot, at, new Vector2(CardW, CardH));

        var glow = MakeImage(slot, "Glow", new Color(accent.r, accent.g, accent.b, 0f));
        glow.sprite = MenuArt.GlowRect(26f);
        glow.type = Image.Type.Sliced;      // else the falloff scales with the card
        Stretch(glow.rectTransform, inset: -26f);

        var body = MakeImage(slot, "Body", CardBed);
        body.sprite = MenuArt.RoundedRect(12f);
        body.type = Image.Type.Sliced;
        body.raycastTarget = true;          // this is the button
        Stretch(body.rectTransform);
        // The mask's alpha-clipped stencil is what rounds the art's corners.
        body.gameObject.AddComponent<Mask>().showMaskGraphic = true;

        var art = new GameObject("Art").AddComponent<RawImage>();
        art.rectTransform.SetParent(body.transform, false);
        art.texture = Resources.Load<Texture2D>("Menu/" + mode.art);
        art.color = new Color(0.82f, 0.82f, 0.82f, 1f);
        Stretch(art.rectTransform);

        var shade = MakeImage(body.transform, "Shade", new Color(0f, 0f, 0f, 0.88f));
        shade.sprite = MenuArt.FadeUp();
        Band(shade.rectTransform, top: false, height: 58f);

        var label = MakeText(body.transform, "Label", mode.label, 16,
            new Color(1f, 1f, 1f, 0.82f), FontStyle.Bold, Vector2.zero, Vector2.zero);
        var labelRect = label.rectTransform;
        labelRect.anchorMin = new Vector2(0f, 0f);
        labelRect.anchorMax = new Vector2(1f, 0f);
        labelRect.pivot = new Vector2(0.5f, 0f);
        labelRect.offsetMin = new Vector2(11f, 9f);
        labelRect.offsetMax = new Vector2(-11f, 33f);
        label.alignment = TextAnchor.MiddleLeft;

        var accentIdle = new Color(accent.r, accent.g, accent.b, 0.55f);
        var rail = MakeImage(body.transform, "Accent", accentIdle);
        Band(rail.rectTransform, top: false, height: 3f);

        var button = body.gameObject.AddComponent<Button>();
        // The card animates itself; Selectable's colour tint would fight it.
        button.transition = Selectable.Transition.None;
        button.onClick.AddListener(mode.go);

        var card = body.gameObject.AddComponent<MenuCard>();
        card.lift = slot;
        card.art = art;
        card.accent = rail;
        card.glow = glow;
        card.label = label;
        card.accentIdle = accentIdle;
        card.accentHot = accent;
    }

    // -- footer ----------------------------------------------------------

    static void BuildFooter(Transform parent, GameModeController controller)
    {
        var rule = MakeImage(parent, "FooterRule", new Color(1f, 1f, 1f, 0.10f));
        Place(rule.rectTransform, new Vector2(0f, -392f), new Vector2(1736f, 1f));

        // Counted, not typed: a roster or a deck can change without leaving a
        // stale boast on the title screen.
        var roster = controller.GetComponent<RobotRoster>();
        int heroes = roster != null && roster.robots != null ? roster.robots.Length : 0;
        var tally = MakeText(parent, "Tally", $"{_modeCount}  BATTLE  MODES   ·   {heroes}  HEROES", 17,
            new Color(1f, 1f, 1f, 0.38f), FontStyle.Bold, Vector2.zero, new Vector2(420f, 26f));
        Corner(tally.rectTransform, new Vector2(0f, 0f), new Vector2(92f, 40f));
        tally.alignment = TextAnchor.MiddleLeft;

        _hint = MakeText(parent, "Hint", DesktopHint, 19, new Color(1f, 1f, 1f, 0.42f),
            FontStyle.Normal, Vector2.zero, new Vector2(1300f, 28f));
        Corner(_hint.rectTransform, new Vector2(0.5f, 0f), new Vector2(0f, 39f));

        BuildSeedBox(parent);
    }

    /// <summary>
    /// The MAP CODE entry, tucked into the bottom-right corner: blank rolls
    /// a fresh battlefield, a code rebuilds a known one. Read by Commander
    /// and Tower Defense both.
    /// </summary>
    static void BuildSeedBox(Transform parent)
    {
        // Caption beside the box, both centred on the footer row's baseline —
        // stacked above it they crossed the footer rule.
        var caption = MakeText(parent, "SeedLabel", "MAP  CODE", 15,
            new Color(1f, 1f, 1f, 0.42f), FontStyle.Bold, Vector2.zero, new Vector2(160f, 22f));
        Corner(caption.rectTransform, new Vector2(1f, 0f), new Vector2(-330f, 42f));
        caption.alignment = TextAnchor.MiddleRight;

        var box = MakeImage(parent, "SeedBox", new Color(0.04f, 0.09f, 0.15f, 0.92f));
        box.sprite = MenuArt.RoundedRect(6f);
        box.type = Image.Type.Sliced;
        box.raycastTarget = true;           // this is the text field
        Corner(box.rectTransform, new Vector2(1f, 0f), new Vector2(-118f, 34f));
        box.rectTransform.sizeDelta = new Vector2(200f, 38f);

        var underline = MakeImage(box.transform, "Underline", new Color(0.25f, 0.84f, 1f, 0.55f));
        Band(underline.rectTransform, top: false, height: 2f, inset: 6f);

        var text = MakeText(box.transform, "Text", "", 20, Color.white, FontStyle.Normal,
            Vector2.zero, new Vector2(184f, 34f));
        var placeholder = MakeText(box.transform, "Placeholder", "random", 20,
            new Color(1f, 1f, 1f, 0.28f), FontStyle.Italic, Vector2.zero, new Vector2(184f, 34f));

        _seedField = box.gameObject.AddComponent<InputField>();
        _seedField.targetGraphic = box;
        _seedField.textComponent = text;
        _seedField.placeholder = placeholder;
        _seedField.characterLimit = 7;
        _seedField.contentType = InputField.ContentType.IntegerNumber;
    }

    /// <summary>
    /// Swap the control hint when the input scheme changes (TouchControls calls
    /// this). Null restores the keyboard wording.
    /// </summary>
    public static void SetHint(string hint)
    {
        if (_hint != null)
            _hint.text = string.IsNullOrEmpty(hint) ? DesktopHint : hint;
    }

    /// <summary>
    /// The project's one rounded panel sprite. Any runtime screen that wants
    /// soft corners (Chinese Quest's answer cards, the Tank Raid HUD) shares
    /// this rather than generating a second texture at a slightly different
    /// radius.
    /// </summary>
    public static Sprite RoundedTile() => MenuArt.RoundedRect(16f);

    // -- rect plumbing ---------------------------------------------------

    static RectTransform MakeRect(Transform parent, string name)
    {
        var go = new GameObject(name);
        go.transform.SetParent(parent, false);
        return go.AddComponent<RectTransform>();
    }

    static Image MakeImage(Transform parent, string name, Color color)
    {
        var go = new GameObject(name);
        go.transform.SetParent(parent, false);
        var img = go.AddComponent<Image>();
        img.color = color;
        img.raycastTarget = false;
        return img;
    }

    static Text MakeText(Transform parent, string name, string content, int size, Color color,
        FontStyle style, Vector2 position, Vector2 sizeDelta)
    {
        var go = new GameObject(name);
        go.transform.SetParent(parent, false);
        var text = go.AddComponent<Text>();
        text.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        text.text = content;
        text.fontSize = size;
        text.fontStyle = style;
        text.color = color;
        text.alignment = TextAnchor.MiddleCenter;
        // No label on this screen is clickable in its own right — the cards
        // are clicked through their frame, and the map-code field through its
        // box — so none of them should be eating raycasts.
        text.raycastTarget = false;
        // Titles are laid out by hand; wrapping or clipping them to their rect
        // would silently rewrap a lockup that is already positioned.
        text.horizontalOverflow = HorizontalWrapMode.Overflow;
        text.verticalOverflow = VerticalWrapMode.Overflow;
        Place(text.rectTransform, position, sizeDelta);
        return text;
    }

    /// <summary>Centre-anchored placement, the default for this canvas.</summary>
    static void Place(RectTransform rect, Vector2 position, Vector2 size)
    {
        rect.anchorMin = rect.anchorMax = new Vector2(0.5f, 0.5f);
        rect.anchoredPosition = position;
        rect.sizeDelta = size;
    }

    /// <summary>Pinned to one corner or edge of the parent instead.</summary>
    static void Corner(RectTransform rect, Vector2 anchor, Vector2 position)
    {
        rect.anchorMin = rect.anchorMax = rect.pivot = anchor;
        rect.anchoredPosition = position;
    }

    static void Stretch(RectTransform rect, float inset = 0f)
    {
        rect.anchorMin = Vector2.zero;
        rect.anchorMax = Vector2.one;
        rect.offsetMin = new Vector2(inset, inset);
        rect.offsetMax = new Vector2(-inset, -inset);
    }

    /// <summary>A full-width strip floating at a given height on the canvas.</summary>
    static void Strip(RectTransform rect, float centreY, float height)
    {
        rect.anchorMin = new Vector2(0f, 0.5f);
        rect.anchorMax = new Vector2(1f, 0.5f);
        rect.pivot = new Vector2(0.5f, 0.5f);
        rect.sizeDelta = new Vector2(0f, height);
        rect.anchoredPosition = new Vector2(0f, centreY);
    }

    /// <summary>A full-width strip along the top or bottom edge.</summary>
    static void Band(RectTransform rect, bool top, float height, float inset = 0f)
    {
        rect.anchorMin = new Vector2(0f, top ? 1f : 0f);
        rect.anchorMax = new Vector2(1f, top ? 1f : 0f);
        rect.pivot = new Vector2(0.5f, top ? 1f : 0f);
        rect.offsetMin = new Vector2(inset, top ? -height : 0f);
        rect.offsetMax = new Vector2(-inset, top ? 0f : height);
    }

    static void EnsureEventSystem()
    {
        if (Object.FindFirstObjectByType<UnityEngine.EventSystems.EventSystem>() == null)
        {
            var es = new GameObject("EventSystem");
            es.AddComponent<UnityEngine.EventSystems.EventSystem>();
            es.AddComponent<UnityEngine.EventSystems.StandaloneInputModule>();
        }
    }
}
